name: jrosarybibleapp
base: core22
version: '1.2.3'
summary: A simple Bible app. # 79 char long summary
description: |
  A simple Bible app. This projects goal is to promote spiritual health, and to allow each person to study the bible and come to their own conclusion about their faith.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  rosary:
    command: bin/rosary
    extensions: [gnome]
    desktop: usr/share/applications/rosary.desktop

parts:
  prep:
    plugin: dump
    source: https://github.com/RoseBlume/Rosary/releases/download/v1.2.3/rosary_1.2.3_amd64.deb
    source-type: deb
    override-pull: |
      set -eu
      craftctl default
      sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" usr/share/applications/rosary.desktop
    organize:
      usr/bin/rosary: bin/rosary
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      - libsoup-3.0-0
      - freeglut3
