name: jrosarybibleapp
base: core22
adopt-info: metapart
version: '2.0.2'
summary: Read the Bible and other Christian texts. # 79 char long summary
description: |
  Study the Bible, and read Christianity related works. This projects goal is to promote spiritual health, and to allow each person to study the bible and come to their own conclusion about their faith.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
apps:
  rosary:
    command: bin/rosary
    desktop: usr/share/applications/rosary.desktop

parts:
  metapart:
    plugin: dump
    source: .
    parse-info: [extra/io.github.roseblume.rosary.xml]
  comppart:
    plugin: dump
    source: .
    build-packages:
    - libwebkit2gtk-4.0-dev
    - build-essential
    # - libsoup-3.0-dev
    # - libjavascriptcoregtk-4.1-dev
    - curl
    - wget
    - file
    - libssl-dev
    - libgtk-3-dev
    - libayatana-appindicator3-dev
    - librsvg2-dev
    - binutils
    - xz-utils
    - dpkg
    stage-packages:
    - libwebkit2gtk-4.1-0
    - libglu1-mesa
    - libsoup-3.0-0
    - freeglut3
    build-snaps:
    - rustup/latest/stable
    - node/20/stable
    override-pull: |
      set -eu
      craftctl default
      rustup default nightly
      echo -e "Finished setting up rust"
      echo -e "\nPrepping\n"
      mv prep/v1/nightly/Cargo.toml src-tauri/Cargo.toml
      mv prep/v1/tauri.conf.json src-tauri/tauri.conf.json
      mv prep/v1/vite.config.js vite.config.json
      mv prep/v1/package.json package.json
      rm package-lock.json
      npm install
      echo -e "Finished installing frontend deps"
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/deb/*.deb here
      mkdir deb
      mv src-tauri/target/release/deb/here/usr deb
      sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" deb/usr/share/applications/rosary.desktop
    organize:
      deb/usr/bin/rosary: bin/rosary
      deb/usr/share/applications/rosary.desktop: usr/share/applications/rosary.desktop
      deb/usr/share/icons/hicolor/32x32/apps/rosary.png: usr/share/icons/hicolor/32x32/apps/rosary.png
      deb/usr/share/icons/hicolor/128x128/apps/rosary.png: usr/share/icons/hicolor/128x128/apps/rosary.png
      deb/usr/share/icons/hicolor/256x256@2/apps/rosary.png: usr/share/icons/hicolor/256x256@2/apps/rosary.png

    #   prep:
#     plugin: dump
#     build-packages:
#       - npm
#       - nodejs
#     source:
#       - on amd64 to amd64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.2/rosary_2.0.2_amd64.deb
#       - on arm64 to arm64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.2/rosary_2.0.2_arm64.deb
#     source-type: deb
#     override-pull: |
#       set -eu
#       craftctl default
#       sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" usr/share/applications/rosary.desktop
#     organize:
#       usr/bin/rosary: bin/rosary
#     stage-packages:
#       - libwebkit2gtk-4.1-0
#       - libglu1-mesa
#       - libsoup-3.0-0
#       - libglut3.12
    #   prep:
#     plugin: dump
#     build-packages:
#       - npm
#       - nodejs
#     source:
#       - on amd64 to amd64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.2/rosary_2.0.2_amd64.deb
#       - on arm64 to arm64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.2/rosary_2.0.2_arm64.deb
#     source-type: deb
#     override-pull: |
#       set -eu
#       craftctl default
#       sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" usr/share/applications/rosary.desktop
#     organize:
#       usr/bin/rosary: bin/rosary
#     stage-packages:
#       - libwebkit2gtk-4.1-0
#       - libglu1-mesa
#       - libsoup-3.0-0
#       - libglut3.12
