name: rosary # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

apps:
  rosary:
    command: bin/rosary
    extensions: [gnome]
    desktop: usr/share/applications/rosary.desktop

parts:
  prep:
    plugin: dump
    source: https://github.com/RoseBlume/Rosary/releases/download/v1.2.3/rosary_1.2.3_amd64.deb
    source-type: deb
    override-pull: |
      set -eu
      craftctl default
      sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" usr/share/applications/rosary.desktop
    organize:
      usr/bin/rosary: bin/rosary
      #usr/share/icons/hicolor/32x32/apps/rosary.png: rosary.png
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      #- libjavascriptcoregtk-4.1-0
      - libsoup-3.0-0
      - freeglut3
      # - libssl-dev
      #- libgtk-3-dev
      #- libayatana-appindicator3-dev
      #- librsvg2-dev
  #webkit:
    #plugin: dump
    #source: http://security.debian.org/debian-security/pool/updates/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.44.1-1~deb12u1_amd64.deb
    #source-type: deb
    #stage-packages:
    #  - libxorg
    #   - libatk
    #   - libavif
    #   - libcairo
    #   #- libenchant
    #   #- libepoxy
    #   - libfontconfig
    #   #- libgbm
    #   #- libgdk
    #   #- libgstallocators
    #   #- libgstapp
    #   #- libgstaudio
    #   #- libgstbase
    #   #- libgstfft
    #   #- libgstgl
    #   #- libgstpbutils
    #   - libgstreamer
    #   #- libgsttag
    #   #- libgsttranscoder
    #
