name: ArchCompile

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - name: Docker hello-world
      run: |
        sudo pacman --noconfirm -Syu docker
        git clone https://github.com/RoseBlume/Rosary.git
        cd Rosary
        sudo pacman -S --noconfirm rustup nodejs npm
        npm install
        npm run tauri build
        sudo systemctl start docker
        docker run --rm hello-world
