name: Danctnix

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v4
        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
            cache: 'npm' # Set this to npm, yarn or pnpm.

        - name: Rust cache
          uses: swatinem/rust-cache@v2
          with:
            workspaces: './src-tauri -> target'

        - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
          run: npm install # change this to npm or pnpm depending on which one you use.

        - name: add icons
          run: npm run tauri icon Bible3.png
        
        - uses: tauri-apps/tauri-action@v0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
            releaseName: 'Full Release v__VERSION__'
            releaseBody: 'See the assets to download this version and install.'
            releaseDraft: false
            prerelease: false
            args: ${{ matrix.settings.args }}

    # Add your build and test steps here
    # ...
